"""
Chat API endpoints for customer support conversations.

Handles chat messages with streaming support via Server-Sent Events.
"""
import json
import logging
import time
import uuid
from typing import AsyncGenerator, Dict, Any, Optional

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.config import get_settings
from app.core.orchestrator import process_message
from app.utils.rate_limiter import RateLimiter, RateLimitExceeded

logger = logging.getLogger(__name__)
settings = get_settings()
rate_limiter = RateLimiter()

router = APIRouter()


class ChatRequest(BaseModel):
    """Request model for chat endpoint."""
    message: str
    session_id: Optional[str] = None
    conversation_history: list[Dict[str, str]] = []
    metadata: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    """Response model for chat endpoint."""
    response: str
    session_id: str
    intent: str
    tokens_used: int
    elapsed_time: float


@router.post("/")
async def chat_endpoint(request: ChatRequest) -> ChatResponse:
    """
    Process a chat message and return a response.
    
    This endpoint processes user messages through the orchestrator,
    which handles intent classification, RAG retrieval, tool execution,
    and response generation.
    """
    # Generate session ID if not provided
    session_id = request.session_id or str(uuid.uuid4())
    
    # Check rate limit
    try:
        await rate_limiter.check_rate_limit(session_id)
    except RateLimitExceeded as e:
        raise HTTPException(status_code=429, detail=str(e))
    
    start_time = time.time()
    
    try:
        # Process message through orchestrator
        result = await process_message(
            message=request.message,
            session_id=session_id,
            conversation_history=request.conversation_history,
        )
        
        elapsed_time = time.time() - start_time
        
        return ChatResponse(
            response=result["response"],
            session_id=session_id,
            intent=result.get("intent", "unknown"),
            tokens_used=result.get("tokens_used", 0),
            elapsed_time=elapsed_time,
        )
    except Exception as e:
        logger.error(f"Error processing chat message: {e}")
        raise HTTPException(status_code=500, detail="Failed to process message")


@router.post("/stream")
async def chat_stream_endpoint(request: ChatRequest) -> StreamingResponse:
    """
    Process a chat message with streaming response via SSE.
    
    Returns a stream of tokens as they are generated by the LLM.
    """
    # Generate session ID if not provided
    session_id = request.session_id or str(uuid.uuid4())
    
    # Check rate limit
    try:
        await rate_limiter.check_rate_limit(session_id)
    except RateLimitExceeded as e:
        raise HTTPException(status_code=429, detail=str(e))
    
    async def generate() -> AsyncGenerator[str, None]:
        """Generate SSE events."""
        try:
            async for event in process_message_stream(
                message=request.message,
                session_id=session_id,
                conversation_history=request.conversation_history,
            ):
                # Format as SSE event
                yield f"data: {json.dumps(event)}\n\n"
            
            # Send end signal
            yield "data: [DONE]\n\n"
        except Exception as e:
            logger.error(f"Error in streaming response: {e}")
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


async def process_message_stream(
    message: str,
    session_id: str,
    conversation_history: list[Dict[str, str]],
) -> AsyncGenerator[Dict[str, Any], None]:
    """
    Process message and stream tokens as they are generated.
    
    This is a simplified streaming implementation. For production,
    you would integrate with LangGraph's streaming capabilities.
    """
    start_time = time.time()
    
    # Send processing status
    yield {
        "type": "status",
        "message": "Processing your request...",
    }
    
    try:
        # Process through orchestrator (non-streaming for now)
        result = await process_message(
            message=message,
            session_id=session_id,
            conversation_history=conversation_history,
        )
        
        # Send intent classification
        yield {
            "type": "intent",
            "intent": result.get("intent", "unknown"),
        }
        
        # Stream the response character by character (simulated)
        response_text = result.get("response", "")
        for char in response_text:
            yield {
                "type": "token",
                "token": char,
            }
        
        # Send completion
        yield {
            "type": "complete",
            "response": response_text,
            "session_id": session_id,
            "tokens_used": result.get("tokens_used", 0),
            "elapsed_time": time.time() - start_time,
        }
        
    except Exception as e:
        yield {
            "type": "error",
            "error": str(e),
        }
